sudo: required
services:
  - docker
language: node_js
node_js: 10
branches:
  only:
    - master
addons:
  ssh_known_hosts: "$HOST"
before_install:
  - openssl aes-256-cbc -K $encrypted_ba14c54caeb1_key -iv $encrypted_ba14c54caeb1_iv
    -in id_rsa.enc -out ~/.ssh/id_rsa -d
install:
  - yarn install
script:
  - yarn run docs:build
  - docker build -t jolylai/notebook-flutter .
  - docker login -u $DOCKER_NAME -p $DOCKER_PASSWORD
  - docker push jolylai/notebook-flutter
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local_dir: docs/.vuepress/dist
  on:
    branch: master
after_deploy:
  - chmod 600 ~/.ssh/id_rsa
  - scp -o "StrictHostKeyChecking no" -i id_rsa docker-compose.yml root@$HOST:/root/
  - ssh -o "StrictHostKeyChecking no" -i id_rsa root@$HOST "cd /root/;sudo docker-compose -f docker-compose.yml pull;sudo docker-compose -f docker-compose.yml up -d;exit"
  # - ssh -o "StrictHostKeyChecking no" -i id_rsa root@$HOST "rm -rf /root/docker-compose.yml"
